#!groovy

// Generated by IBM TransformationAdvisor
// Wed Mar 27 16:15:43 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}